[workspace]
members = [
  "crates/bin/",
  "crates/file/",
  "crates/linker/",
  "crates/object/",
  "crates/object-macros/",
  "crates/scheduler/",
]

[workspace.dependencies]
smol = "1.3.0"
thiserror = "1.0"