[package]
name = "weld-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
thiserror = { workspace = true }

[features]
default = []

# Enable the diagnostics API.
diagnostics = []

[lints]
workspace = true
